export const SET_NEW_RELEASED_MOVIES = 'SET_NEW_RELEASED_MOVIES';
export const SET_POPULAR_MOVIES = 'SET_POPULAR_MOVIES';
export const SET_NOW_PLAYING_MOVIES = 'SET_NOW_PLAYING_MOVIES';
export const SET_TOP_RATED_MOVIES = 'SET_TOP_RATED_MOVIES';

export const SET_TOP_HEADLINES = 'SET_TOP_HEADLINES';
export const SET_TRENDING_HEADLINES = 'SET_TRENDING_HEADLINES';

export const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE';
export const SET_SEAT_DETAILS = 'SET_SEAT_DETAILS';

export const SET_TICKET_LIST = 'SET_TICKET_LIST';
